### ISSUE TITLE
Report abuse link

### ISSUE THREAD

**Issue by glsee** [piotrkulpinski/openalternative#10]
I like the Open Alternative and actually signed up for many products there.
But I'm very bothered by the fact that some of the products don't even exist yet. They are just a web page to conduct smoke tests and have nothing to claim that they are 'open source alternative to <<a famous product>>'.

Can we have a report abuse button to report and have those fake products taken down?

**Comment by piotrkulpinski** [comment]
Sure, I can add something like that. Do you have any examples of such products featured on the site?

**Comment by glsee** [comment]
A few that I might have encountered: Badget, Ziggy, Maybe.
