### ISSUE TITLE
Wrong categorization for product: Pika

### ISSUE THREAD

**Issue by jfunez** [piotrkulpinski/openalternative#13]
Checking the API Platform category, it list "Pika" and description says: "Free screenshot editor for creating beautiful images and mockups".

Clearly, nothing related to APIs.

Product page: https://openalternative.co/tool/pika/
Screenshot of the current categories:
![image](https://github.com/piotrkulpinski/openalternative/assets/805749/9c3086ee-b646-4eab-8102-fcf9bfc8ac0e)

**Comment by ctrimm** [comment]
I think that this can be closed out. I was unable to reproduce the issue. I think @piotrkulpinski updated the data in the DB.

<img width="1095" alt="Screenshot 2024-03-20 at 6 25 22 AM" src="https://github.com/piotrkulpinski/openalternative/assets/1751160/208e1690-4fd8-40bd-a6b4-55d73db1ab8b">
