### ISSUE TITLE
404 Page Not Found for Tool `vrite`

### ISSUE THREAD

**Issue by ctrimm** [piotrkulpinski/openalternative#15]
Steps to Reproduce:
- Navigate to [https://openalternative.co/languages](https://openalternative.co/languages)
- Click on Astro
- Verify that `Vrite` shows up with a card (see screenshot below)
- Click on `Vrite` card
- 404 page rendered for URL - [https://openalternative.co/tool/vrite](https://openalternative.co/tool/vrite)

<img width="908" alt="Screenshot 2024-03-20 at 6 33 03 AM" src="https://github.com/piotrkulpinski/openalternative/assets/1751160/e62b4712-25a7-47ce-87d1-3b5438de7934">

**Comment by piotrkulpinski** [comment]
Thank you for reporting! Should be fixed now.
