### ISSUE TITLE
CRON_SECRET , cron jobs

### ISSUE THREAD

**Issue by Ishfaq-Techverx** [piotrkulpinski/openalternative#22]
Im runing this project **[openalternative](https://github.com/piotrkulpinski/openalternative)** locally , 

- Its not fetching accurate details as given on production, its missing some data

- secondly , may be i am missing **CRON_SECRET** 

- Im clueless how to get this key and from where
-  Can some one suggest solution?

**Comment by piotrkulpinski** [comment]
Hi, 
You have to set up the CRON_SECRET in your `env` file. It can be any unique string. It's a security layer so that no one can trigger the cron job outside of your application. 

You also have to set up the cron job somewhere. I run it on Vercel, but you can use Upstash, Cloudflare or anything else.

Hope that helps.

**Comment by piotrkulpinski** [comment]
> @piotrkulpinski I have deployed the project on Vercel, will the cron jobs run automatically or do I have to follow extra steps?

Yup, you should be good to go. There's a [vercel.json](https://github.com/piotrkulpinski/openalternative/blob/main/vercel.json) file so it sets everything automatically. You can confirm by going to Settings -> Cron Jobs in your Vercel project.

**Comment by Ishfaq-Techverx** [comment]
@piotrkulpinski  Thanks sir for your time and valuable response 

I am facing an issue when i run locally this repo, I dont get complete data of related repos, e,g starpi data is fetched but partial, its stars, forks,languages details ,iconurl is coming null

why it is so , any particular reason if I am missing something while running this?

**Comment by piotrkulpinski** [comment]
@Ishfaq-Techverx Did you set up other environment variables listed in `.env.example`? When you run the cron job manually, does it display any errors?

**Comment by Ishfaq-Techverx** [comment]
@piotrkulpinski  yes I have all the other variables in .env file,the secret keys

my deployed APP **:https://osrepo.vercel.app/**

if you see this page , there is a data difference , might be you can guide better after this view

**Comment by piotrkulpinski** [comment]
@Ishfaq-Techverx Looks like the `fetch-repository` script didn't run at all. Please check in your vercel account if it ran and if yes, there should be some error displayed which can help you debug the issue.

**Comment by faisalseraj** [comment]
@piotrkulpinski thanks for your valuable response, but the issue still exists, I think this issue is not resolved yet. 

Can you please guide on how to trigger the cron jobs manually? How to run the fetch-repository script locally?

**Comment by Ishfaq-Techverx** [comment]
@piotrkulpinski  hello sir

I believe in **routes folder** of the project and then a file there with name :**api.fetch-repository.ts** this is something which is related to fetch repos, This API does'nt call at all, can you please guide me when does it runs?

anyway to tun this manually , because my data isnt fetching in **DB** 

Your response is much appreciated

**Comment by piotrkulpinski** [comment]
@faisalseraj @Ishfaq-Techverx 
The `/api/fetch-repository` is triggered from the cron job for every tool found in the database. If you've set it up correctly on Vercel, the `/api/cron` endpoint should be called automatically at midnight, fetch all of your tools from the database, and trigger `/api/fetch-repository` for every tool found.

This is how your vercel Cron settings should look like:
![CleanShot 2024-04-09 at 09 11 09](https://github.com/piotrkulpinski/openalternative/assets/358412/dde1d151-bde4-485e-9d4e-5ebb52af2541)

If you want to trigger the fetch manually (or locally) use any HTTP client like Insomnia or Postman and run the endpoint with following settings: 
![CleanShot 2024-04-09 at 09 13 18](https://github.com/piotrkulpinski/openalternative/assets/358412/113d077c-f8ff-4121-984c-2848b7ec4a95)

Remember to set Authentication to Bearer token and add your `CRON_SECRET` there.

That's unfortunately all I can help you with.
