### ISSUE TITLE
Website includes non-open-source projects

### ISSUE THREAD

**Issue by ssddanbrown** [piotrkulpinski/openalternative#23]
Hello,
I raised this [on your Reddit post](https://www.reddit.com/r/opensource/comments/1b9kl7m/comment/ktxapfu/) but opening up here since there was no response there.

Just wanted to raise that a few of the projects lists would not widely be considered open source, while you are essentially promoting them under as open source. I've written my views about why I'd consider this important [on my blog here](https://danb.me/blog/why-open-source-term-is-important/).

Browsing through the homepage list, I can see the following applications which I know wouldn't meet the commonly considered [open source definition](https://opensource.org/osd), although this is not a thorough check:

- N8N
- Sentry
- Outline
- Airbyte
- Budibase is questionable now [from my last look into it](https://github.com/Budibase/budibase/discussions/12377).
- Erxes
- Nango

**Comment by ssddanbrown** [comment]
Just adding some extra context as to why these would not be considered open source [as requested via Reddit](https://www.reddit.com/r/opensource/comments/1ekhuvr/comment/lgl2wwy/).

- N8N - [License](https://github.com/n8n-io/n8n/blob/master/LICENSE.md) limits use & modification to certain audiences, and certion modifications to all.
- Sentry - [License](https://github.com/getsentry/sentry/blob/master/LICENSE.md) prevents certain use-cases until the software becomes open source after two years.
- Outline - [License](https://github.com/outline/outline/blob/main/LICENSE) prevents certain uses-cases until the software becomes open source after about 4 years.
- Airbyte - [License](https://github.com/airbytehq/airbyte/blob/master/LICENSE) prevents certain use-cases and limits modification.
- Budibase - [Doesn't seem](https://github.com/Budibase/budibase/discussions/12377) to be buildable from its open source code alone, requires non-open code.
- Erxes - [License](https://github.com/erxes/erxes/blob/v2/LICENSE.md) adds limitations against certain use-cases.
- Nango - [License](https://github.com/NangoHQ/nango/blob/master/LICENSE) prevents certain use-cases and limits modification.

Generally speaking, open-source as per the [commonly regarded OSD](https://opensource.org/osd) allows open use, modification & distribution.
Therefore projects that limit those freedoms are not widely considered open source, but fall into source available.
If helpful, i've written about why I believe this distinction to be important [here on my blog](https://danb.me/blog/open-source-available-distinction/).

**Comment by ssddanbrown** [comment]
> Generally, most of the projects listed on the site are for-profit companies. Hence, they might have restrictions on certain use cases.

But most don't have to restrict use-cases, since they're actually open source offering.

My concern is that your whole website is centered around providing open source alternatives, which is what visitors come here for, so including those still propagates misrepresentation of open source. You can have a range of "openess", but "open source" isn't really a range itself, it's the full set of open rights (use, modification & distribution) that makes open source what it is. If you add a mark, to make it clear to uses I feel it would have to effectively state the project is not open source, which is then awkward to have an a site specifically for open source alternatives.

>  I believe there is still a lot of value we can derive from these codebases/companies, so I would like to keep them visible on the site.

The website seems to be focused on providing open source alternatives to non-open offerings. I'd have thought the target audience there is people looking for open source alternatives to use, rather than non open source codebases/companies to inspect. Is the value of keeping them on the site for that use-case worth the added confusion in scope and to users?

**Comment by piotrkulpinski** [comment]
Thanks for the valuable feedback! 

I just removed N8N as it's clearly not open source. I will continue to check and monitor other tools in the directory and will develop a way to "report a tool" soon.

Closing this for now.
