### ISSUE TITLE
Link rss feed in <head>

### ISSUE THREAD

**Issue by KAGEYAM4** [piotrkulpinski/openalternative#31]
I almost missed rss icon and thought the site dosen't provide rss feed as i use https://addons.mozilla.org/en-US/firefox/addon/want-my-rss/ to detect rss feeds on site.

Can you add rss as <link> in <head> similar to https://blog.mozilla.org/en/

**Comment by piotrkulpinski** [comment]
Should be fixed now 👍 Thanks for reporting the issue
