### ISSUE TITLE
Inngest

### ISSUE THREAD

**Issue by emersonlaurentino** [piotrkulpinski/openalternative#4]
Hi,
First of all, congrats for that. It's awasome.

Now, I thinking the trigger.dev isn't alternative to inngest directly, because both is open source.

ref: [inngest repository](https://github.com/inngest/inngest)

btw, Inngest must be in the list too.

**Comment by piotrkulpinski** [comment]
You're totally right! Didn't know Inngest is Open Source too. 
Just added it to the list and remove as "alternative".

https://openalternative.co/tool/inngest/
