### ISSUE TITLE
Remove Pipedream? 

### ISSUE THREAD

**Issue by jnv** [piotrkulpinski/openalternative#8]
Hi, thank you for this project!

I noticed that you [list Pipedream](https://openalternative.co/tool/pipedream/) as an alternative to Zapier and Make. However I'd like to point out that this is not really an open-source project. You can't take Pipedream and self-host it. There are only [vague promises](https://github.com/PipedreamHQ/pipedream/issues/954#issuecomment-1219881717) that self-hosting will be available eventually. What's contained in the repository are pre-built integrations. Furthermore, the code isn't even open-source under some OSI-approved license, but [in 2023 switched](https://pipedream.com/blog/introducing-the-pipedream-source-available-license/) to their proprietary source-available license.

So yeah, I'm not sure what are your criteria for including a project, but I don't see how Pipedream fits on this list.

**Comment by piotrkulpinski** [comment]
Thanks for the explanation. I didn't look close enough into this project when I posted it. Just removed from the website.

**Comment by inthevortex** [comment]
@piotrkulpinski hey, just noticed it is present in the section when I use filter for "python". Is that by mistake?

**Comment by KazeroG** [comment]
Reopen because the projects page still online : https://openalternative.co/pipedream

it's not open source anymore as they are considering put it as Premium feature

https://github.com/PipedreamHQ/pipedream/issues/954#issuecomment-2129893358

**Comment by juandl** [comment]
Yes remove, i saw and i though was true, but they wont do self host

**Comment by jnv** [comment]
@juandl @adryserage Folks, consider creating a new issue, unfortunately I can't reopen this one.

**Comment by piotrkulpinski** [comment]
Thank you for bringing that up! I've already removed it months ago, but it must have been restored when I was using a backup database dump some time ago.

Anyway, I've just removed it completely, and it should no longer be visible on the site.
